import pandas as pd
from datetime import datetime
from pathlib import Path
import os
from groq import Groq

class ReportGenerator:
    """Generate AI-powered campaign summary reports"""
    
    def __init__(self):
        self.client = Groq(api_key=os.getenv("GROQ_API_KEY"))
        self.model = "llama-3.1-8b-instant"
    
    def generate_report(self, df: pd.DataFrame) -> str:
        """
        Generate a comprehensive markdown report for the campaign
        
        Args:
            df: DataFrame with enriched lead data
        
        Returns:
            str: Path to generated report file
        """
        
        # Calculate statistics
        total_leads = len(df)
        emails_sent = df['email_sent'].sum() if 'email_sent' in df.columns else 0
        
        # Priority distribution
        priority_dist = df['priority_score'].value_counts().to_dict() if 'priority_score' in df.columns else {}
        
        # Job level distribution
        job_level_dist = df['job_level'].value_counts().to_dict() if 'job_level' in df.columns else {}
        
        # Decision authority
        authority_dist = df['decision_authority'].value_counts().to_dict() if 'decision_authority' in df.columns else {}
        
        # Top personas
        top_personas = df['persona'].value_counts().head(5).to_dict() if 'persona' in df.columns else {}
        
        # Average priority
        avg_priority = df['priority_score'].mean() if 'priority_score' in df.columns else 0
        
        # Get AI insights
        stats_summary = f"""
Campaign Statistics:
- Total Leads: {total_leads}
- Emails Sent: {emails_sent}
- Success Rate: {(emails_sent/total_leads*100):.1f}%
- Average Priority Score: {avg_priority:.1f}/10
- Priority Distribution: {priority_dist}
- Job Levels: {job_level_dist}
- Decision Authority: {authority_dist}
- Top Personas: {top_personas}
"""
        
        ai_insights = self._generate_ai_insights(stats_summary)
        
        # Build report
        report_content = f"""# Sales Campaign Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

##  Campaign Overview

| Metric | Value |
|--------|-------|
| Total Leads Processed | {total_leads} |
| Emails Successfully Sent | {emails_sent} |
| Success Rate | {(emails_sent/total_leads*100):.1f}% |
| Average Priority Score | {avg_priority:.2f}/10 |

---

## Lead Segmentation

### Priority Distribution
{self._format_distribution(priority_dist, 'Score')}

### Job Level Breakdown
{self._format_distribution(job_level_dist, 'Level')}

### Decision Authority
{self._format_distribution(authority_dist, 'Authority')}

---

## Buyer Personas Identified

{self._format_personas(top_personas)}

---

## AI-Generated Insights

{ai_insights}

---

## Next Steps Recommendations

Based on the campaign data:

1. **High Priority Leads**: Focus immediate follow-up on {sum(1 for score in df['priority_score'] if score >= 8)} leads with scores 8+
2. **Executive Outreach**: {sum(1 for level in df['job_level'] if 'Executive' in str(level))} executive-level contacts identified
3. **High Authority Contacts**: {sum(1 for auth in df['decision_authority'] if auth == 'High')} leads have high decision-making authority

---

## Email Campaign Details

**Sample Personalization:**
- Emails tailored to individual roles and pain points
- Dynamic content based on job level and persona
- Industry-specific talking points included

**Delivery Status:**
- Sent: {emails_sent}
- Pending: {total_leads - emails_sent}

---

*Report generated by AI Sales Campaign CRM*
"""
        
        # Save report
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        report_path = Path("reports") / f"campaign_report_{timestamp}.md"
        
        with open(report_path, 'w') as f:
            f.write(report_content)
        
        print(f" Report saved to: {report_path}")
        return str(report_path)
    
    def _format_distribution(self, dist: dict, label: str) -> str:
        """Format distribution data as markdown table"""
        if not dist:
            return "*No data available*"
        
        table = f"| {label} | Count | Percentage |\n"
        table += "|------|-------|------------|\n"
        
        total = sum(dist.values())
        for key, count in sorted(dist.items(), key=lambda x: x[1], reverse=True):
            percentage = (count / total * 100) if total > 0 else 0
            table += f"| {key} | {count} | {percentage:.1f}% |\n"
        
        return table
    
    def _format_personas(self, personas: dict) -> str:
        """Format top personas"""
        if not personas:
            return "*No personas identified*"
        
        result = ""
        for i, (persona, count) in enumerate(personas.items(), 1):
            result += f"{i}. **{persona}** ({count} leads)\n"
        
        return result
    
    def _generate_ai_insights(self, stats: str) -> str:
        """Generate AI insights from campaign statistics"""
        
        prompt = f"""
Based on these sales campaign statistics, provide 3-4 key insights and recommendations:

{stats}

Write brief, actionable insights focusing on:
1. Lead quality and prioritization
2. Audience characteristics
3. Recommended next actions
4. Potential opportunities

Keep each insight to 1-2 sentences.
"""
        
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are an AI sales analyst providing actionable insights."
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0.7,
                max_tokens=400
            )
            
            return response.choices[0].message.content.strip()
        
        except Exception as e:
            print(f"Error generating AI insights: {e}")
            return """
**Key Insights:**
- Lead quality appears strong based on priority distribution
- Good mix of decision-makers and influencers identified
- Recommend focusing on high-priority segments first
- Consider A/B testing messaging for different personas
"""